export const FOLDERS_FETCH_REQUEST = 'FOLDERS_FETCH_REQUEST';
export const FOLDERS_FETCH_SUCCESS = 'FOLDERS_FETCH_SUCCESS';
export const FOLDERS_FETCH_FAILURE = 'FOLDERS_FETCH_FAILURE';
export const FOLDERS_FETCH_EXIT = 'FOLDERS_FETCH_EXIT';
export const FOLDERS_SET_CURRENT_PAGE = 'FOLDERS_SET_CURRENT_PAGE';
export const FOLDERS_FILTER_REQUEST = 'FOLDERS_FILTER_REQUEST';

export const FOLDERS_CLEAR_PAGE_CACHE = 'FOLDERS_CLEAR_PAGE_CACHE';